- name: Demo on first playbook
  hosts: all
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World



#Variable declaration at play level
- name: Play level varibale
  hosts: all
  vars:
    URL: play.example.com
  tasks:
      - name: print URL
        ansible.builtin.debug:
          msg: variable - {{ URL }}

#Variable declaration at task level
- name: Task level varibale
  hosts: all
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: variable - {{ URL }}
  vars:
    URL: task.example.com



#Variable declaration at task level
- name: Play level variable
  hosts: all
  vars.files:
    -exvars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: variable - {{ URL }}










